# Generated by Django 3.1.1 on 2022-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=180)),
                ('usage', models.CharField(max_length=180)),
                ('rainFallType', models.CharField(max_length=180)),
                ('skyType', models.CharField(max_length=180)),
                ('windDirection', models.CharField(max_length=180)),
                ('windSpeed', models.CharField(max_length=180)),
                ('humidity', models.CharField(max_length=180)),
                ('Temperature', models.CharField(max_length=180)),
                ('elevation', models.CharField(max_length=180)),
                ('radiation', models.CharField(max_length=180)),
                ('VaporPressure', models.CharField(max_length=180)),
                ('surfaceTemperature', models.CharField(max_length=180)),
                ('AtmospherePressure', models.CharField(max_length=180)),
                ('Bulbs', models.CharField(max_length=180)),
                ('Fan', models.CharField(max_length=180)),
                ('Iron', models.CharField(max_length=180)),
                ('TV', models.CharField(max_length=180)),
                ('Refrigerator', models.CharField(max_length=180)),
                ('Blender', models.CharField(max_length=180)),
                ('airConditioner', models.CharField(max_length=180)),
                ('waterHeater', models.CharField(max_length=180)),
                ('microwaveOven', models.CharField(max_length=180)),
                ('riceCooker', models.CharField(max_length=180)),
            ],
        ),
    ]
