# Generated by Django 3.1.1 on 2022-10-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfMembers', models.IntegerField()),
                ('noOofTimesUsingTheIron', models.IntegerField()),
                ('noOfTimesUsingTheWashingMachine', models.IntegerField()),
                ('firstmonthUnits', models.IntegerField()),
                ('secondMonthUnits', models.IntegerField()),
                ('thirdMonthUnits', models.IntegerField()),
                ('firstMonthCost', models.FloatField()),
                ('secondMonthCost', models.FloatField()),
                ('thirdMonthCost', models.FloatField()),
                ('averageUnits', models.FloatField()),
                ('microwave_Yes', models.IntegerField()),
                ('hairDryer_Yes', models.IntegerField()),
                ('electricOven_Yes', models.IntegerField()),
                ('windowType_Yes', models.IntegerField()),
                ('waterGeyser_Yes', models.IntegerField()),
                ('electricWaterHeater_Yes', models.IntegerField()),
                ('cielingFan_Yes', models.IntegerField()),
                ('standFan_Yes', models.IntegerField()),
                ('tableFan_Yes', models.IntegerField()),
                ('exhaustFan_Yes', models.IntegerField()),
            ],
        ),
    ]
